# See https://prek.j178.dev for more information
# yaml-language-server: $schema=https://www.schemastore.org/prek.json
repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: cef8b8350da46d8114c7e6b7272aebdccdf193ce  # frozen: v1.30.0
    hooks:
      - id: zizmor
