// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Rotates credentials. It maintains `timestamps` and an `index` into them; when the timestamp at `index` is older than `rotationPeriodDays`, the cursor advances to the next slot and that slot is re-stamped with the current time.
 */
export class MultiRotate extends pulumi.CustomResource {
    /**
     * Get an existing MultiRotate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): MultiRotate {
        return new MultiRotate(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'multirotate:index:MultiRotate';

    /**
     * Returns true if the given object is an instance of MultiRotate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MultiRotate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MultiRotate.__pulumiType;
    }

    /**
     * Number of timestamps in the rotation window.
     */
    declare public readonly count: pulumi.Output<number>;
    /**
     * The timestamp at `timestamps[index]`.
     */
    declare public /*out*/ readonly currentTimestamp: pulumi.Output<string>;
    /**
     * Index of the last rotated timestamp.
     */
    declare public /*out*/ readonly index: pulumi.Output<number>;
    /**
     * Number of days a timestamp stays valid before it is rotated.
     */
    declare public readonly rotationPeriodDays: pulumi.Output<number>;
    /**
     * The rotation window: `count` ISO-8601 timestamps.
     */
    declare public /*out*/ readonly timestamps: pulumi.Output<string[]>;

    /**
     * Create a MultiRotate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: MultiRotateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["count"] = (args?.count) ?? 1;
            resourceInputs["rotationPeriodDays"] = (args?.rotationPeriodDays) ?? 60;
            resourceInputs["currentTimestamp"] = undefined /*out*/;
            resourceInputs["index"] = undefined /*out*/;
            resourceInputs["timestamps"] = undefined /*out*/;
        } else {
            resourceInputs["count"] = undefined /*out*/;
            resourceInputs["currentTimestamp"] = undefined /*out*/;
            resourceInputs["index"] = undefined /*out*/;
            resourceInputs["rotationPeriodDays"] = undefined /*out*/;
            resourceInputs["timestamps"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MultiRotate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a MultiRotate resource.
 */
export interface MultiRotateArgs {
    /**
     * Number of timestamps in the rotation window.
     */
    count?: pulumi.Input<number | undefined>;
    /**
     * Number of days a timestamp stays valid before it is rotated.
     */
    rotationPeriodDays?: pulumi.Input<number | undefined>;
}
